---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: ciao-universe-deployment
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: ciao-universe-app
    spec:
      containers:
        - name: ciao-universe
          image: ciao-universe:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080